# Generated by Django 5.2.4 on 2026-01-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdminCreatedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("userid", models.CharField(max_length=200)),
                ("usertype", models.CharField(max_length=50)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="patient",
            name="assigned_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="final_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="tat",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="parent_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_users",
                to="med.useraccount",
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="profile_picture",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="signature_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="signature_disclaimer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="signature_image",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="usertype",
            field=models.CharField(
                choices=[
                    ("RADS", "RADS"),
                    ("IMAGING", "IMAGING"),
                    ("SUPERADMIN", "Super Admin"),
                    ("ADMIN", "Admin"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_text", models.TextField(blank=True)),
                ("status", models.CharField(default="DRAFT", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="med.useraccount",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="med.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
