# Generated by Django 5.2.4 on 2026-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0002_superadmincreatedusers_patient_assigned_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="scan_image",
        ),
        migrations.AddField(
            model_name="patient",
            name="scan_images",
            field=models.TextField(default="[]"),
        ),
    ]
