# Generated by Django 5.2.4 on 2026-01-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0003_remove_patient_scan_image_patient_scan_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="scan_image",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
