# Generated by Django 5.2.4 on 2026-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0021_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
