# Generated by Django 5.2.4 on 2026-01-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0022_useraccount_email_useraccount_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
